#!/bin/bash

# just get the latest Drupal with wget. No drush dependency.

set -e          # Exit immediately if a command exits with a non-zero status.

VER=7                                           # Drupal major version
PAGE="https://www.drupal.org/project/drupal"    # Drupal web page with latest versions

# get the link to the latest file for the specified major version
LNAME=`wget -q -O - ${PAGE} | sed '/drupal-'${VER}'.[0-9]*.tar.gz/!d; s/^[^\"]*\"//; s/\".*$//;'`

DRUPAL_DIR=${OPENSHIFT_DATA_DIR}drupal
DRUPAL_SITE_DIR=${OPENSHIFT_DATA_DIR}sites

mkdir -p ${OPENSHIFT_TMP_DIR}drupal
mkdir -p ${OPENSHIFT_DATA_DIR}downloads

# download and expand .tar.gz
(cd ${OPENSHIFT_DATA_DIR}downloads ; wget -q ${LNAME})
LATEST=$(ls -1t ${OPENSHIFT_DATA_DIR}downloads | head -1)
(cd ${OPENSHIFT_DATA_DIR}downloads ; tar -xf ${LATEST})

# Link the /current symlink to the latest Drupal instance
LATEST=`echo ${LATEST} | sed 's/.tar.gz//;'`
export DRUPAL_INSTALL_DIR="${OPENSHIFT_DATA_DIR}downloads/${LATEST}"
ln -s ${LATEST} ${OPENSHIFT_DATA_DIR}downloads/current

# ####
# modify Drupal
mv $DRUPAL_INSTALL_DIR/sites $DRUPAL_INSTALL_DIR/sites.original
# NEED line 58-91
# install Health Check
# ###
