#!/bin/bash

# deploy Drupal

set -e          # Exit immediately if a command exits with a non-zero status.

# load some Openshift functions
source $OPENSHIFT_CARTRIDGE_SDK_BASH

DRUPAL_SITE_DIR=${OPENSHIFT_DATA_DIR}sites
DRUPAL_PRIVATE_DIR=${OPENSHIFT_DATA_DIR}private
DRUPAL_SETTINGS=${DRUPAL_SITE_DIR}/default/settings.php

echo "echo $DRUPAL_SITE_DIR $DRUPAL_PRIVATE_DIR $DRUPAL_SETTINGS"

client_result "echo $DRUPAL_SITE_DIR $DRUPAL_PRIVATE_DIR $DRUPAL_SETTINGS"

# lines 26 - 133
